services:
  - type: web
    name: xmi-stream-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: BOT_TOKEN
        value: "8636298353:AAG51fEmR_gKaj8kZ09NV_p-833RJfE5dPU"
      - key: CHANNEL_ID
        value: "-1004415998750"
      - key: API_ID
        value: "34704016"
      - key: API_HASH
        value: "68a7cd3c57fe18aedc2a29984183a29e"
